backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"

collections:
  - name: "lesson"
    label: "Lesson"
    folder: "_lessons"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Unit"
        name: "unit"
        widget: "relation"
        collection: "unit"
        searchFields: ["title", "description"]
        valueField: "order"
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "unit"
    label: "Unit"
    folder: "_units"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Description", name: "description", widget: "markdown"}
